# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0002_auto_20170918_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='user_id',
            new_name='user',
        ),
    ]
