# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes_books', '0003_auto_20170918_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='uploader',
            new_name='uploaded_by',
        ),
    ]
